/**
 * The demo cast.
 *
 * ## Provenance - read this before trusting a field
 *
 * The `identity`, `psych` and `voice` blocks of all three payloads below are **verbatim
 * model output**. They were generated on **2026-08-23** by:
 *
 * ```
 * cd apps/cli
 * OLLAMA_HOST=http://127.0.0.1:11434 npx tsx src/main.ts character "<premise>"
 * ```
 *
 * against `qwen3.5:latest` on a local Ollama, through `StructuredCall`'s extract →
 * validate → repair loop, and each came back `resolution clean, attempts 1, repairs 0`
 * (76 s, 195 s and 201 s; $0.00). The three premises are quoted above each sheet.
 *
 * **`--full` was tried first and failed**, which is why it is not used here: asking
 * `qwen3.5` for a whole `CharacterPayload` in one turn produced no JSON at all across four
 * attempts and three repair turns (350 s, `No JSON object or array found in model output`) -
 * exactly the failure `character.ts`'s own header predicts, and the reason the command
 * defaults to the CHIRON core. So the four remaining blocks - `arc`, `visual`,
 * `motionSignature` and `knowledgeScope` - are **authored by hand**, from the psychology
 * the model produced. They are not model output and are not labelled as such anywhere.
 *
 * The model returned empty `virtues`, `flaws`, `fears` and `values` on all three sheets.
 * They are left empty. Filling them in would make the file prettier and would make the
 * provenance note above false.
 *
 * To regenerate, run the three commands quoted below and replace the three blocks. The
 * envelope fields (`canonicalName`, `aliases`, `summary`, `firstAppearance`, `importance`,
 * `assetRefs`) are the seed's own bookkeeping and are authored in every case.
 */

import type {
  CharacterPayload,
  EntityAssetLink,
  EntityId,
  Importance,
  StoryTime,
} from '@rv/contracts';

/**
 * One seeded character: the graph envelope plus the sheet.
 *
 * The id lives on the sheet rather than in a lookup table next to it because the seed is
 * re-runnable and the ids are therefore fixed: keeping the id beside the character it names
 * is what stops the two lists drifting the day a fourth character is added.
 */
export interface DemoCharacterSheet {
  readonly id: EntityId;
  readonly canonicalName: string;
  readonly aliases: readonly string[];
  readonly summary: string;
  readonly firstAppearance: StoryTime;
  readonly importance: Importance;
  readonly assetRefs: readonly EntityAssetLink[];
  readonly payload: CharacterPayload;
}

/**
 * Fixed entity ids, exported so the relation table can name its endpoints.
 *
 * Cast rather than parsed, unlike the ids in `demo-seed.ts`: these three are re-parsed a
 * moment later by `Entity.parse` when the envelope is validated, so a typo still fails at
 * the boundary and a second `EntityId.parse` here would only fail it twice.
 */
export const DEMO_GOLAB_ID = 'ent_0DEM0GR0VE0000000000000010' as EntityId;
export const DEMO_GOLNAR_ID = 'ent_0DEM0GR0VE0000000000000011' as EntityId;
export const DEMO_FARHAD_ID = 'ent_0DEM0GR0VE0000000000000012' as EntityId;

/**
 * Premise given to `rv character` for بی‌بی گلاب:
 *
 * > A Persian folk tale set in a walled pomegranate grove outside a desert town. The grove
 * > keeper is an old woman who has watered the trees alone for forty years and talks to
 * > them by name; she refuses to let anyone else draw from the well because of something
 * > she buried there.
 */
const GOLAB: DemoCharacterSheet = {
  id: DEMO_GOLAB_ID,
  canonicalName: 'بی‌بی گلاب',
  aliases: ['باغبان پیر', 'بی‌بی', 'زنِ چاه'],
  summary:
    'چهل سال است تنها باغ انار را آب می‌دهد و هر درخت را به نامش صدا می‌زند. کسی حق ندارد از چاه بردارد، و او هرگز نگفته چرا. مهربانی‌اش شبیه نگهبانی است و نگهبانی‌اش شبیه ترس.',
  firstAppearance: { ordinal: 10, label: 'قسمت ۱ — شب اول' },
  importance: 'lead',
  assetRefs: [
    { semanticKey: 'char/bibi-golab/base', role: 'turnaround' },
    { semanticKey: 'char/bibi-golab/base', role: 'portrait' },
  ],
  payload: {
    // ── generated by `rv character` against qwen3.5, 2026-08-23 ──────────────
    identity: {
      age: 'late seventies',
      gender: 'female',
      species: 'human',
      occupation: 'Grove Keeper',
      origin: 'The Walled Pomegranate Grove',
    },
    psych: {
      want: "To protect the grove's water at all costs and ensure no one else suffers the fate she did.",
      need: 'To trust that others can handle their own burdens without her interference, allowing her to let go of control.',
      wound:
        "She believes that if she doesn't guard everything herself, disaster will strike and innocent lives will be lost.",
      lie: 'I am the only one who knows how to keep this place safe; anyone else is a danger to the water.',
      ghost:
        "The death of her beloved husband, whom she buried in the well because he was dying of thirst and she feared sharing his fate with him if she didn't seal him there first.",
      virtues: [],
      flaws: [],
      fears: [],
      values: [],
      temperament: {
        warmth: 0,
        dominance: 1,
        volatility: -1,
        openness: -1,
        conscientiousness: 1,
      },
    },
    voice: {
      register: 'neutral',
      verbosity: 'measured',
      idiolect: [
        'botanical names for every tree in the grove',
        'references to root systems and soil depth',
        'metaphors involving water flow and drought',
      ],
      verbalTics: ['answers questions with observations about the weather or the trees'],
      profanity: 'none',
      sentenceRhythm: 'flowing',
      humourMode: 'none',
      silenceHabits:
        "She speaks only when necessary, her voice dropping to a whisper when the wind shifts through the leaves. Her silence is not empty; it is heavy with the weight of forty years of listening to trees that cannot speak back. When she goes quiet, she is calculating whether the current situation threatens the well's seal.",
    },
    // ── authored, from the psychology above ─────────────────────────────────
    arc: {
      startState:
        'Locks the well every dusk, counts the buckets, and turns visitors away at the gate with a bowl of fruit so they do not ask a second time.',
      endState:
        'Unlocks the well in front of a witness and says out loud what is in it, and lets someone else carry the first bucket.',
      turningPoints: [],
    },
    visual: {
      silhouetteNote:
        'A stooped column wrapped to the ankles, widening at the hip where a rope coil always hangs; the head reads as a single soft wedge because the chador never leaves it.',
      build: 'slight',
      height: 'a head shorter than everyone she argues with',
      palette: [
        { name: 'pomegranate rind', hex: '#7c2b21', role: 'primary' },
        { name: 'sun-bleached indigo', hex: '#4a5a72', role: 'secondary' },
        { name: 'well-rope hemp', hex: '#c8a878', role: 'neutral' },
      ],
      distinguishingMarks: [
        'rope burn across both palms, old and white',
        'a nail missing on the left hand',
      ],
      wardrobe: [
        {
          slug: 'wardrobe-default',
          label: 'کار روزانه',
          description:
            'A faded indigo chador tucked into the waist so both hands stay free, over a rust-coloured tunic mended at the elbows; bare feet in split rubber sandals, a hemp rope always coiled at the hip.',
          validity: { from: null, until: null },
          palette: [
            { name: 'sun-bleached indigo', hex: '#4a5a72', role: 'primary' },
            { name: 'pomegranate rind', hex: '#7c2b21', role: 'accent' },
          ],
        },
      ],
      expressionSet: [
        {
          slug: 'guarding',
          label: 'نگهبان',
          description:
            'Chin down, eyes up and fixed; jaw set so the mouth is a single line; both hands closed at the hips rather than crossed.',
          intensity: 0.7,
        },
        {
          slug: 'caught-out',
          label: 'مچ‌گرفته',
          description:
            'Brows lift for half a beat then drop hard; the mouth opens on nothing; one hand goes to the rope coil without her deciding to.',
          intensity: 0.8,
        },
        {
          slug: 'talking-to-a-tree',
          label: 'گفت‌وگو با درخت',
          description:
            'Whole face slack and open, head tilted up into the branches, eyes half closed - the only time her shoulders drop.',
          intensity: 0.5,
        },
      ],
      poseSet: [
        {
          slug: 'at-the-wellhead',
          label: 'کنار چاه',
          description:
            'Squatting on both heels with one forearm across the well lip, the other arm hanging straight down inside the shaft.',
          intensity: 0.6,
        },
        {
          slug: 'barring-the-gate',
          label: 'سدِ دروازه',
          description:
            'Standing square in the gateway, weight even, one hand flat against each jamb so the whole opening is her.',
          intensity: 0.9,
        },
      ],
      propAffinities: [
        {
          label: 'the hemp rope at her hip',
          note: 'She re-coils it whenever a conversation turns towards the well, which is how the audience learns the well is what the conversation is about.',
        },
      ],
    },
    motionSignature: {
      gaitStyle: 'trudge',
      posture: 'hunched',
      gestureFrequency: 0.2,
      energy: 0.35,
      idleBehaviour:
        'Rests one hand flat on the nearest trunk and stays there, weight on the back foot, head turning slowly along the row as if taking a count.',
      tellOnLying:
        'Her free hand finds the rope coil and starts tightening it a turn at a time while her voice stays perfectly level.',
    },
    knowledgeScope: 'limited',
  },
};

/**
 * Premise given to `rv character` for گلنار:
 *
 * > A Persian folk tale set in a walled pomegranate grove outside a desert town. A
 * > barefoot orphan girl of about eleven who climbs the grove wall every night to steal
 * > fruit, and who can hear the trees answer back - a gift she hides because the town
 * > would call it sorcery.
 */
const GOLNAR: DemoCharacterSheet = {
  id: DEMO_GOLNAR_ID,
  canonicalName: 'گلنار',
  aliases: ['دخترکِ دیوار', 'گل'],
  summary:
    'یازده‌ساله، پابرهنه، هر شب از دیوار باغ بالا می‌رود. انار می‌دزدد و صدای درخت‌ها را می‌شنود؛ هیچ‌کدام را به کسی نگفته است. شبِ اول چیزی دید که هنوز نمی‌داند با آن چه کند.',
  firstAppearance: { ordinal: 10, label: 'قسمت ۱ — شب اول' },
  importance: 'lead',
  assetRefs: [
    { semanticKey: 'char/golnar/base', role: 'turnaround' },
    { semanticKey: 'char/golnar/base', role: 'portrait' },
  ],
  payload: {
    // ── generated by `rv character` against qwen3.5, 2026-08-23 ──────────────
    identity: {
      age: '11',
      gender: 'female',
      species: 'human',
      occupation: 'fruit thief',
      origin: 'the walled pomegranate grove',
    },
    psych: {
      want: 'to be seen as a clever, useful member of the town who can solve problems.',
      need: 'to be allowed to listen to the trees and trust that nature speaks truth without judgment.',
      wound:
        'her ability to hear the trees was discovered by her cruel aunt, who threatened to burn her for sorcery if she ever spoke of it again.',
      lie: 'if I stay silent and hide my gift, no one will hurt me or take away my freedom.',
      ghost:
        'the night my aunt dragged me back from the wall and threatened to throw me into the well when a branch whispered my name.',
      virtues: [],
      flaws: [],
      fears: [],
      values: [],
      temperament: {
        warmth: 0,
        dominance: -1,
        volatility: 0,
        openness: 1,
        conscientiousness: 1,
      },
    },
    voice: {
      register: 'neutral',
      verbosity: 'measured',
      idiolect: ['tree names', 'root metaphors'],
      verbalTics: ['answers with a question about the wind'],
      profanity: 'none',
      sentenceRhythm: 'flowing',
      humourMode: 'dry',
      silenceHabits:
        'She only speaks when absolutely necessary, her voice dropping to a whisper whenever she hears the trees rustling. When threatened, she goes completely silent, refusing to answer questions because answering might reveal the secret of her hearing.',
    },
    // ── authored, from the psychology above ─────────────────────────────────
    arc: {
      startState:
        'Steals at night and lies by day, and answers every direct question with a question so she never has to hold a position.',
      endState:
        'Says out loud, to a person who can use it against her, what she heard the trees say - and stays standing there afterwards.',
      turningPoints: [],
    },
    visual: {
      silhouetteNote:
        'All elbows and knees under a tunic two sizes too big, with one long uneven braid that swings out ahead of her whenever she turns.',
      build: 'slight',
      height: 'shoulder-high to an adult',
      palette: [
        { name: 'unripe pomegranate', hex: '#8f9c53', role: 'primary' },
        { name: 'dust', hex: '#b9a690', role: 'neutral' },
        { name: 'stolen-fruit red', hex: '#a83b2e', role: 'accent' },
      ],
      distinguishingMarks: [
        'permanently scabbed knees from the wall',
        'soles too hard for sandals',
      ],
      wardrobe: [
        {
          slug: 'wardrobe-default',
          label: 'لباس شب‌گردی',
          description:
            "An adult's olive tunic cut down at the hem and belted with rope, sleeves pushed past the elbow and knotted; no shoes, ever, and a shawl worn as a sling for carrying fruit.",
          validity: { from: null, until: null },
          palette: [
            { name: 'unripe pomegranate', hex: '#8f9c53', role: 'primary' },
            { name: 'dust', hex: '#b9a690', role: 'neutral' },
          ],
        },
      ],
      expressionSet: [
        {
          slug: 'listening',
          label: 'گوش‌سپرده',
          description:
            'Head turned so one ear leads, eyes unfocused on nothing, lips parted; the whole face goes still in a way no eleven-year-old face should.',
          intensity: 0.6,
        },
        {
          slug: 'caught',
          label: 'گیرافتاده',
          description:
            'Eyes wide and fixed on the exit rather than the person, weight already shifting to the back foot, mouth clamped shut.',
          intensity: 0.85,
        },
        {
          slug: 'sly',
          label: 'موذی',
          description:
            'One corner of the mouth up, brows level, chin tucked - the look she uses instead of answering.',
          intensity: 0.5,
        },
      ],
      poseSet: [
        {
          slug: 'astride-the-wall',
          label: 'روی دیوار',
          description:
            'Straddling the top of the wall, one bare foot braced on the inner face, both hands flat on the coping, torso pitched forward.',
          intensity: 0.8,
        },
        {
          slug: 'crouched-in-the-rows',
          label: 'چمباتمه میان ردیف‌ها',
          description:
            'Folded down between two trunks with the shawl-sling pulled into her chest, heels off the ground, ready to bolt.',
          intensity: 0.7,
        },
      ],
      propAffinities: [
        {
          label: 'the shawl she carries fruit in',
          note: 'She knots and unknots it while thinking; when she puts it down, she has decided to stay.',
        },
      ],
    },
    motionSignature: {
      gaitStyle: 'prowl',
      posture: 'coiled',
      gestureFrequency: 0.35,
      energy: 0.8,
      idleBehaviour:
        'Never fully still - shifts weight foot to foot, picks at the shawl knot, and checks the wall line every few seconds without turning her head.',
      tellOnLying:
        'She answers a question with a question about the weather, exactly the way the old woman does, and only ever when she is lying.',
    },
    knowledgeScope: 'limited',
  },
};

/**
 * Premise given to `rv character` for میرزا فرهاد:
 *
 * > A Persian folk tale set in a walled pomegranate grove outside a desert town. A polite
 * > young water-surveyor sent from the capital to measure the grove's well and sign it over
 * > to the canal works. He believes he is doing a kindness, and carries a forged deed he
 * > has not read.
 */
const FARHAD: DemoCharacterSheet = {
  id: DEMO_FARHAD_ID,
  canonicalName: 'میرزا فرهاد',
  aliases: ['مهندسِ آب', 'فرهاد', 'مردِ کاغذها'],
  summary:
    'بیست‌وچهار ساله، از پایتخت، با یک جعبه ابزار نقشه‌برداری و سندی که هرگز تا آخر نخوانده است. مؤدب، دقیق، و کاملاً مطمئن که دارد به این مردم لطف می‌کند.',
  firstAppearance: { ordinal: 30, label: 'قسمت ۳ — ورود مهندس' },
  importance: 'supporting',
  assetRefs: [
    { semanticKey: 'char/mirza-farhad/base', role: 'turnaround' },
    { semanticKey: 'char/mirza-farhad/base', role: 'portrait' },
  ],
  payload: {
    // ── generated by `rv character` against qwen3.5, 2026-08-23 ──────────────
    identity: {
      age: '24',
      gender: 'male',
      species: 'human',
      occupation: 'water-surveyor',
      origin: 'The Capital',
    },
    psych: {
      want: "To secure the grove's title for the Canal Works to ensure proper irrigation and prevent future disputes.",
      need: 'To admit that his authority is a fabrication and that he must listen to the land and its people rather than imposing order from above.',
      wound:
        "He was raised on stories of the Capital's benevolent rule, believing that structure and paperwork are the only things that protect the weak from chaos.",
      lie: 'If I sign this deed correctly, I am saving these people; my signature is a shield against their poverty.',
      ghost:
        "The day he was sent to the grove, his mentor told him, 'A man without a stamp is a man without a voice,' and he took it as absolute truth.",
      virtues: [],
      flaws: [],
      fears: [],
      values: [],
      temperament: {
        warmth: 0,
        dominance: 1,
        volatility: -1,
        openness: -1,
        conscientiousness: 1,
      },
    },
    voice: {
      register: 'formal',
      verbosity: 'measured',
      idiolect: ["surveyor's jargon", 'geometric metaphors', 'references to ink and parchment'],
      verbalTics: ['corrects his own grammar mid-sentence'],
      profanity: 'none',
      sentenceRhythm: 'balanced',
      humourMode: 'none',
      silenceHabits:
        'He speaks only when the wind stops, using pauses to calculate if his words will hold weight. When he is truly afraid of being wrong, he goes silent and stares at the water lines, letting the silence scream for him.',
    },
    // ── authored, from the psychology above ─────────────────────────────────
    arc: {
      startState:
        'Reads the measurement aloud before he reads the room, and hands over the deed with both hands as though it were a gift.',
      endState:
        'Reads the deed he has been carrying, out loud, to the person it dispossesses - and does not sign it.',
      turningPoints: [],
    },
    visual: {
      silhouetteNote:
        'A narrow vertical broken by one hard horizontal: the surveying rod carried across the shoulders like a yoke, wrists hooked over both ends.',
      build: 'lean',
      height: 'tall enough to have to stoop under the grove gate',
      palette: [
        { name: 'capital grey', hex: '#5c6068', role: 'primary' },
        { name: 'iron-gall ink', hex: '#2b2a33', role: 'shadow' },
        { name: 'parchment', hex: '#e3d7bd', role: 'highlight' },
      ],
      distinguishingMarks: [
        'ink permanently under the right thumbnail',
        'unweathered pale skin above the collar line',
      ],
      wardrobe: [
        {
          slug: 'wardrobe-default',
          label: 'اونیفورم اداری',
          description:
            'A buttoned grey city coat far too heavy for the desert, worn closed on principle; polished shoes already ruined by grove dust, and a leather satchel of rolled paper never set down on the ground.',
          validity: { from: null, until: null },
          palette: [
            { name: 'capital grey', hex: '#5c6068', role: 'primary' },
            { name: 'parchment', hex: '#e3d7bd', role: 'accent' },
          ],
        },
      ],
      expressionSet: [
        {
          slug: 'courteous',
          label: 'مؤدب',
          description:
            'Brows raised a fraction, a small closed-lip smile held a beat too long, eyes doing the actual asking.',
          intensity: 0.5,
        },
        {
          slug: 'recalculating',
          label: 'در حال بازمحاسبه',
          description:
            'Eyes drop to the middle distance, lips move without sound, one hand flattens the paper against his thigh.',
          intensity: 0.65,
        },
        {
          slug: 'undone',
          label: 'فروریخته',
          description:
            'The smile stays and everything under it stops; shoulders come up towards the ears and stay there.',
          intensity: 0.9,
        },
      ],
      poseSet: [
        {
          slug: 'sighting-the-rod',
          label: 'نشانه‌گیری با شاخص',
          description:
            'One eye closed, rod planted vertical, body twisted at the waist with the back foot turned out.',
          intensity: 0.7,
        },
        {
          slug: 'offering-the-deed',
          label: 'تقدیم سند',
          description:
            'Both arms extended level, paper flat across upturned palms, spine straight, head bowed a few degrees.',
          intensity: 0.6,
        },
      ],
      propAffinities: [
        {
          label: 'the folded deed in the satchel',
          note: 'He touches the satchel flap whenever the grove is mentioned, and has still not read past the first page.',
        },
      ],
    },
    motionSignature: {
      gaitStyle: 'march',
      posture: 'rigid',
      gestureFrequency: 0.45,
      energy: 0.55,
      idleBehaviour:
        'Squares the papers against his forearm, aligns his feet to the nearest straight line - a wall, a furrow, a shadow - and waits at attention.',
      tellOnLying:
        'He becomes more precise, not less: the grammar tightens, the numbers get a decimal place they did not need, and he stops blinking.',
    },
    knowledgeScope: 'limited',
  },
};

/** The cast, in first-appearance order. The seed walks this list and nothing else. */
export const DEMO_CHARACTERS: readonly DemoCharacterSheet[] = [GOLAB, GOLNAR, FARHAD];
