/**
 * Delivery, end to end, with the real FFmpeg.
 *
 * One master is rendered from the canvas backend, then cut into every one of the seven
 * verified profiles through a solved reframe plan, and **every output is probed and
 * checked against the profile it claims to satisfy**. That last step is the one this
 * file exists for: producing a file that violates its own spec is the failure the
 * validator catches, and a test that only checked the plan would never see it.
 *
 * The "deliberately wrong output" case is generated by *encoding one wrongly* - a
 * landscape H.264 file handed to the Reels validator - rather than by mocking ffprobe.
 * A mocked probe would only prove the comparison compiles.
 *
 * Kept small: 6 frames at 6 fps from a 480x360 master. Skips loudly if FFmpeg is absent.
 */

import { readFile, rm } from 'node:fs/promises';

import { FixedClock, instant, unwrap } from '@rv/shared-kernel';
import { FORMAT_PRESETS, type FormatProfileId, type JobId } from '@rv/contracts';
import { afterAll, beforeAll, describe, expect, it } from 'vitest';

import { SteppingClock } from '../__fixtures__/doubles';
import { pure2dIr } from '../__fixtures__/ir';
import { scratchDir } from '../__fixtures__/workspace';
import { createNapiCanvasBackend } from '../backends/napi-canvas/napi-canvas-backend';
import { FfmpegEncoder } from '../encode/ffmpeg-encoder';
import { FfprobeReader } from '../encode/ffprobe';
import { NodeProcessRunner } from '../encode/node-process';
import { InMemoryCheckpointStore } from '../job/checkpoint-stores';
import { InMemoryFrameStore } from '../job/frame-stores';
import { RunRenderJobUseCase } from '../job/render-job';
import type { ShotTiming } from '../reframe/reframe-filter';
import type { ShotFraming } from '../reframe/solve-crop';
import { FileArtifactStore } from './artifact-store';
import { DeliverEpisodeUseCase, deliveryFingerprint, type DeliverInput } from './deliver';
import { masterSettings } from './encode-settings';
import { validateAgainstProfile } from './spec-validator';

const MASTER_SIZE = { width: 480, height: 360 };
const FPS = 6;
const DURATION_MS = 1000;
const ALL_FORMATS = Object.keys(FORMAT_PRESETS) as FormatProfileId[];

const SHOT_A = 'sht_0000000000000000000000000A';
const SHOT_B = 'sht_0000000000000000000000000B';

const runner = new NodeProcessRunner();
const encoder = new FfmpegEncoder(runner);
const prober = new FfprobeReader(runner);

let available = false;
let root = '';
let artifacts: FileArtifactStore;

const MASTER_PATH = 'render/master.mp4';
const MASTER_JOB_ID: JobId = 'job_0000000000000000000000000M';

const SHOTS: readonly ShotFraming[] = [
  {
    shotId: SHOT_A,
    startMs: 0,
    durationMs: 500,
    safeArea: { x: 0.1, y: 0.1, width: 0.8, height: 0.8 },
    focus: [{ timeMs: 0, region: { x: 0.44, y: 0.4, width: 0.12, height: 0.2 } }],
    priority: 'must-keep',
  },
  {
    shotId: SHOT_B,
    startMs: 500,
    durationMs: 500,
    safeArea: { x: 0.1, y: 0.1, width: 0.8, height: 0.8 },
    // A subject that crosses, so at least one shot exercises the pan filter.
    focus: [
      { timeMs: 0, region: { x: 0.06, y: 0.4, width: 0.1, height: 0.2 } },
      { timeMs: 250, region: { x: 0.45, y: 0.4, width: 0.1, height: 0.2 } },
      { timeMs: 500, region: { x: 0.84, y: 0.4, width: 0.1, height: 0.2 } },
    ],
    priority: 'must-keep',
  },
];

const TIMINGS: readonly ShotTiming[] = [
  { shotId: SHOT_A, startMs: 0, durationMs: 500 },
  { shotId: SHOT_B, startMs: 500, durationMs: 500 },
];

function deliverInput(overrides: Partial<DeliverInput> = {}): DeliverInput {
  return {
    masterPath: MASTER_PATH,
    masterSize: MASTER_SIZE,
    animationId: 'anm_fixture',
    frameCount: FPS,
    outputDir: 'deliver/e01',
    formats: ALL_FORMATS,
    reframe: { composition: MASTER_SIZE, shots: SHOTS },
    timings: TIMINGS,
    ...overrides,
  };
}

function useCase(): DeliverEpisodeUseCase {
  return new DeliverEpisodeUseCase({
    encoder,
    prober,
    artifacts,
    clock: new FixedClock(instant(1_760_000_000_000)),
  });
}

beforeAll(async () => {
  root = await scratchDir('deliver-e2e');
  artifacts = new FileArtifactStore(root);

  const probe = await encoder.probeAvailable();
  available = probe.ok;
  if (!available) {
    console.warn('SKIPPING the delivery end-to-end suite: no runnable ffmpeg on PATH.');
    return;
  }

  // A real master, drawn by the real canvas backend.
  const job = new RunRenderJobUseCase({
    renderers: new Map([['napi-canvas', createNapiCanvasBackend()]]),
    frames: new InMemoryFrameStore(),
    checkpoints: new InMemoryCheckpointStore(),
    encoder,
    clock: new SteppingClock(),
  });
  unwrap(
    await job.execute({
      jobId: MASTER_JOB_ID,
      ir: pure2dIr({ fps: FPS, durationMs: DURATION_MS }),
      size: MASTER_SIZE,
      backend: 'napi-canvas',
      frames: null,
      master: {
        outputPath: unwrap(await artifacts.prepareWrite(MASTER_PATH)),
        // H.264 rather than ProRes for the fixture: same code path, a tenth the bytes.
        settings: masterSettings({ fps: FPS, codec: 'h264' }),
      },
    }),
  );
}, 120_000);

afterAll(async () => {
  if (root !== '') await rm(root, { recursive: true, force: true });
});

describe('DeliverEpisodeUseCase', () => {
  it('produces one file per profile plus a manifest, and every file satisfies its spec', async () => {
    if (!available) return;
    const output = unwrap(await useCase().execute(deliverInput()));

    expect(output.manifest.entries).toHaveLength(ALL_FORMATS.length);
    expect(output.manifestPath).toBe('deliver/e01/manifest.json');
    expect(await artifacts.exists(output.manifestPath)).toBe(true);

    for (const entry of output.manifest.entries) {
      const profile = FORMAT_PRESETS[entry.format];
      // The spec check, on the real bytes.
      expect({ format: entry.format, issues: entry.issues }).toEqual({
        format: entry.format,
        issues: [],
      });
      expect(entry.probe.width).toBe(profile.size.width);
      expect(entry.probe.height).toBe(profile.size.height);
      expect(entry.probe.fps).toBeCloseTo(profile.fps, 2);
      expect(entry.artifact.kind).toBe('delivery');
      expect(entry.artifact.sha256).toMatch(/^[0-9a-f]{64}$/);
      expect(entry.artifact.bytes).toBeGreaterThan(0);
      expect(await artifacts.exists(entry.artifact.path)).toBe(true);
    }
  }, 240_000);

  it('delivers Reels as H.264, and nothing else', async () => {
    if (!available) return;
    const output = unwrap(await useCase().execute(deliverInput({ formats: ['reels-9x16'] })));
    expect(output.manifest.entries[0]?.probe.codecName).toBe('h264');
  }, 120_000);

  it('records which strategy each shot was given', async () => {
    if (!available) return;
    const output = unwrap(await useCase().execute(deliverInput({ formats: ['shorts-9x16'] })));
    const strategies = output.manifest.entries[0]?.strategies ?? {};
    expect(Object.keys(strategies).sort()).toEqual([SHOT_A, SHOT_B]);
    // The crossing subject cannot be held by a static crop in 9:16.
    expect(strategies[SHOT_B]).toBe('pan-scan');
  }, 120_000);

  it('is reproducible: delivering the same episode twice gives the same digests', async () => {
    if (!available) return;
    const first = unwrap(await useCase().execute(deliverInput({ formats: ['ig-1x1'] })));
    const second = unwrap(await useCase().execute(deliverInput({ formats: ['ig-1x1'] })));
    expect(second.manifest.entries[0]?.artifact.sha256).toBe(
      first.manifest.entries[0]?.artifact.sha256,
    );
    expect(await readFile(artifacts.resolve(second.manifestPath), 'utf8')).toBe(
      await readFile(artifacts.resolve(first.manifestPath), 'utf8'),
    );
  }, 180_000);

  it('rejects a deliberately wrong output - produced by encoding one wrongly', async () => {
    if (!available) return;
    // Landscape H.264, encoded on purpose, then handed to the Reels validator. No
    // mock anywhere: the file really is 1920x1080 and ffprobe really says so.
    const wrongPath = 'deliver/wrong/landscape.mp4';
    unwrap(
      await encoder.transcode({
        inputPath: artifacts.resolve(MASTER_PATH),
        settings: { ...masterSettings({ fps: FPS, codec: 'h264' }), fps: 30 },
        outputPath: unwrap(await artifacts.prepareWrite(wrongPath)),
        videoFilter: 'scale=1920:1080',
      }),
    );

    const probe = unwrap(await prober.probe(artifacts.resolve(wrongPath)));
    const issues = validateAgainstProfile(probe, FORMAT_PRESETS['reels-9x16']);
    expect(issues.map((issue) => issue.code)).toContain('resolution-mismatch');
    expect(issues.every((issue) => issue.severity === 'error')).toBe(true);
  }, 120_000);

  it('rejects a deliberately wrong codec - HEVC where Instagram takes H.264 only', async () => {
    if (!available) return;
    const wrongPath = 'deliver/wrong/hevc.mp4';
    unwrap(
      await encoder.transcode({
        inputPath: artifacts.resolve(MASTER_PATH),
        settings: {
          ...masterSettings({ fps: FPS, codec: 'h265' }),
          container: 'mp4',
          fps: 30,
          pixelFormat: 'yuv420p',
        },
        outputPath: unwrap(await artifacts.prepareWrite(wrongPath)),
        videoFilter: 'scale=1080:1920',
      }),
    );

    const probe = unwrap(await prober.probe(artifacts.resolve(wrongPath)));
    expect(probe.codecName).toBe('hevc');
    const issues = validateAgainstProfile(probe, FORMAT_PRESETS['reels-9x16']);
    expect(issues.map((issue) => issue.code)).toContain('codec-not-allowed');
  }, 120_000);

  it('fails when the master is not there', async () => {
    const missing = new DeliverEpisodeUseCase({
      encoder,
      prober,
      artifacts,
      clock: new FixedClock(instant(0)),
    });
    const result = await missing.execute(deliverInput({ masterPath: 'render/absent.mov' }));
    expect(result.ok).toBe(false);
  });

  it('fails when a shot has no timing rather than encoding a wrong cut', async () => {
    if (!available) return;
    const result = await useCase().execute(deliverInput({ formats: ['ig-1x1'], timings: [] }));
    expect(result.ok).toBe(false);
    if (result.ok) return;
    expect(result.error.kind).toBe('validation');
  });

  it("fails when the transcode itself fails, carrying FFmpeg's reason", async () => {
    if (!available) return;
    // H.264 in a WebM container: the muxer refuses outright, and the reason has to
    // reach the caller rather than an exit code.
    const result = await useCase().execute(
      deliverInput({
        formats: ['ig-1x1'],
        encodeOverrides: {
          'ig-1x1': {
            ...masterSettings({ fps: FPS, codec: 'h264' }),
            container: 'webm',
            fps: 30,
          },
        },
      }),
    );
    expect(result.ok).toBe(false);
    if (result.ok) return;
    expect(result.error.code).toBe('PROVIDER_ERROR');
  }, 120_000);

  it('fails when the composition has no shots', async () => {
    if (!available) return;
    const result = await useCase().execute(
      deliverInput({ formats: ['ig-1x1'], reframe: { composition: MASTER_SIZE, shots: [] } }),
    );
    expect(result.ok).toBe(false);
  });
});

describe('deliveryFingerprint', () => {
  it('is stable for the same inputs and changes when the framing does', () => {
    const base = deliverInput();
    expect(deliveryFingerprint(base)).toBe(deliveryFingerprint(deliverInput()));
    expect(deliveryFingerprint(base)).not.toBe(
      deliveryFingerprint(deliverInput({ formats: ['ig-1x1'] })),
    );
  });

  it('does not depend on the order the formats were requested in', () => {
    expect(deliveryFingerprint(deliverInput({ formats: ['ig-1x1', 'reels-9x16'] }))).toBe(
      deliveryFingerprint(deliverInput({ formats: ['reels-9x16', 'ig-1x1'] })),
    );
  });
});
