/**
 * Generated bytes in, a transparent canvas plus its quality numbers out.
 *
 * Thin on purpose. The interesting decisions are elsewhere - which engine
 * ({@link ChainedMatting}), what counts as an acceptable cutout (`MatteAcceptance`),
 * what the alpha metrics mean (`raster/alpha`) - and this is the seam that runs them in
 * order and hands the result to the splitter. It exists as a use-case rather than a
 * function because the produce stage is resumable: matting is a step that can be
 * re-entered from the CAS with the generated image already in hand (RV-130).
 */

import { type AppError, type Result, isErr, ok } from '@rv/shared-kernel';
import type { Sha256Hex } from '@rv/contracts';
import type { BlobStore } from '@rv/asset-registry';

import type { MattingEngineId, MattingPort } from '../ports/matting-port';
import type { EncodedImage, RasterPort, RgbaImage } from '../ports/raster-port';
import { alphaCleanliness, alphaCoverage, cornersAreTransparent } from '../raster/alpha';

export interface MatteCanvasDeps {
  readonly raster: RasterPort;
  readonly matting: MattingPort;
  readonly blobs: BlobStore;
}

export interface MatteCanvasInput {
  readonly source: EncodedImage;
  /** The flat field the parts sheet was drawn on, when the lane declared one. */
  readonly backgroundHint?: { readonly r: number; readonly g: number; readonly b: number };
  readonly subject?: string;
  /** Skips the blob write. Used by the splitter, which stores the parts instead. */
  readonly store?: boolean;
}

export interface MatteCanvasOutput {
  readonly image: RgbaImage;
  /** Present when `store` was not false. */
  readonly imageHash: Sha256Hex | undefined;
  readonly engine: MattingEngineId;
  readonly fallbacks: readonly { readonly engine: MattingEngineId; readonly reason: string }[];
  /** Fraction of the canvas the subject occupies. Feeds `QualityScores`. */
  readonly coverage: number;
  /** 1 minus the fraction of stray semi-transparent pixels. Feeds `QualityScores`. */
  readonly cleanliness: number;
  readonly cornersTransparent: boolean;
}

export class MatteCanvasUseCase {
  readonly #deps: MatteCanvasDeps;

  constructor(deps: MatteCanvasDeps) {
    this.#deps = deps;
  }

  async execute(input: MatteCanvasInput): Promise<Result<MatteCanvasOutput, AppError>> {
    const decoded = this.#deps.raster.decode(input.source);
    if (isErr(decoded)) return decoded;

    const matted = await this.#deps.matting.matte({
      image: decoded.value,
      ...(input.backgroundHint === undefined ? {} : { backgroundHint: input.backgroundHint }),
      ...(input.subject === undefined ? {} : { subject: input.subject }),
    });
    if (isErr(matted)) return matted;

    let imageHash: Sha256Hex | undefined;
    if (input.store !== false) {
      const encoded = this.#deps.raster.encode(matted.value.image);
      if (isErr(encoded)) return encoded;
      const put = await this.#deps.blobs.put(encoded.value.data);
      if (isErr(put)) return put;
      imageHash = put.value.hash;
    }

    return ok({
      image: matted.value.image,
      imageHash,
      engine: matted.value.engine,
      fallbacks: matted.value.fallbacks,
      coverage: alphaCoverage(matted.value.image),
      cleanliness: alphaCleanliness(matted.value.image),
      cornersTransparent: cornersAreTransparent(matted.value.image),
    });
  }
}
