import { describe, expect, it } from 'vitest';
import {
  BudgetExceededError,
  InternalError,
  ProviderError,
  isErr,
  isOk,
  nanoUsd,
  unwrap,
} from '@rv/shared-kernel';
import type { AssetDemandPlan, AssetId, AssetKey, AssetVersionId, RunId } from '@rv/contracts';

import {
  FakeBudget,
  FakeImagePort,
  FakePartsSheetPort,
  FakeResolver,
  InMemoryBlobStore,
} from '../__fixtures__/doubles';
import { HASH_A, styleBible, threeBlobSpec } from '../__fixtures__/builders';
import { GenerateAssetVersionUseCase } from './generate-asset-version';

const RUN_ID = 'run_01J8ZQ4E7K9M2N4P6R8T0V2W4X' as RunId;
const KEY = 'c'.repeat(64) as AssetKey;
const ASSET_ID = 'ast_01J8ZQ4E7K9M2N4P6R8T0V2W4X' as AssetId;
const VERSION_ID = 'asv_01J8ZQ4E7K9M2N4P6R8T0V2W4X' as AssetVersionId;

function harness(): {
  useCase: GenerateAssetVersionUseCase;
  images: FakeImagePort;
  budget: FakeBudget;
  resolver: FakeResolver;
  blobs: InMemoryBlobStore;
} {
  const images = new FakeImagePort();
  const budget = new FakeBudget();
  const resolver = new FakeResolver();
  const blobs = new InMemoryBlobStore();
  return {
    useCase: new GenerateAssetVersionUseCase({ resolver, budget, images, blobs }),
    images,
    budget,
    resolver,
    blobs,
  };
}

function hitPlan(): AssetDemandPlan {
  return {
    resolutions: [
      {
        key: KEY,
        spec: threeBlobSpec(),
        outcome: 'cache-hit',
        existingAssetId: ASSET_ID,
        existingVersionId: VERSION_ID,
        styleBibleId: styleBible().id,
        estimatedCostNanoUsd: 0,
      },
    ],
    hitCount: 1,
    missCount: 0,
    totalEstimatedNanoUsd: 0,
    requiresConfirmation: false,
  };
}

describe('GenerateAssetVersionUseCase', () => {
  it('spends nothing on a cache hit: the image port receives zero calls', async () => {
    const { useCase, images, resolver, blobs } = harness();
    resolver.planFor(hitPlan());

    const result = unwrap(
      await useCase.execute({ spec: threeBlobSpec(), style: styleBible(), runId: RUN_ID }),
    );

    expect(result.outcome).toBe('cache-hit');
    // The whole of non-negotiable #2, as an assertion: no call, no bytes, no cost.
    expect(images.callCount).toBe(0);
    expect(blobs.puts).toHaveLength(0);
    if (result.outcome === 'cache-hit') expect(result.costNanoUsd).toBe(0);
  });

  it('generates past a hit only when a regenerate intent is presented', async () => {
    const { useCase, images, resolver } = harness();
    resolver.planFor(hitPlan());

    const result = unwrap(
      await useCase.execute({
        spec: threeBlobSpec(),
        style: styleBible(),
        runId: RUN_ID,
        regenerate: { reason: 'new-take' },
      }),
    );

    expect(result.outcome).toBe('generated');
    expect(images.callCount).toBe(1);
  });

  it('checks the budget before the provider, and refuses without calling it', async () => {
    const { useCase, images, budget } = harness();
    budget.refuseWith(new BudgetExceededError('run', 1, 2));

    const failed = await useCase.execute({
      spec: threeBlobSpec(),
      style: styleBible(),
      runId: RUN_ID,
    });

    expect(isErr(failed)).toBe(true);
    expect(images.callCount).toBe(0);
    expect(budget.checks).toHaveLength(1);
  });

  it('stores the generated bytes and returns their content hash', async () => {
    const { useCase, blobs } = harness();
    const result = unwrap(
      await useCase.execute({ spec: threeBlobSpec(), style: styleBible(), runId: RUN_ID }),
    );

    expect(result.outcome).toBe('generated');
    if (result.outcome !== 'generated') return;
    expect(blobs.puts).toContain(result.imageHash);
    expect(result.request.prompt).toContain('parts sheet');
  });

  it('reports a missing reference as degraded rather than dropping it silently', async () => {
    const { useCase } = harness();
    const spec = threeBlobSpec();
    const result = unwrap(
      await useCase.execute({
        spec,
        style: styleBible(),
        runId: RUN_ID,
        extraReferences: [{ imageHash: HASH_A, role: 'identity-anchor', weight: 1 }],
      }),
    );

    expect(result.outcome).toBe('generated');
    if (result.outcome !== 'generated') return;
    expect(result.degraded.filter((entry) => entry.includes('identity-anchor'))).toHaveLength(1);
  });

  it('passes references it can load through to the provider', async () => {
    const { useCase, images, blobs } = harness();
    const stored = unwrap(await blobs.put(Uint8Array.from([9, 9, 9])));

    await useCase.execute({
      spec: threeBlobSpec(),
      style: styleBible(),
      runId: RUN_ID,
      extraReferences: [{ imageHash: stored.hash, role: 'style-anchor', weight: 1 }],
    });

    expect(images.requests[0]?.references).toHaveLength(1);
  });

  it('propagates a registry failure', async () => {
    const { useCase, resolver, images } = harness();
    resolver.failWith(new InternalError({ message: 'index unavailable' }));

    expect(
      isErr(await useCase.execute({ spec: threeBlobSpec(), style: styleBible(), runId: RUN_ID })),
    ).toBe(true);
    expect(images.callCount).toBe(0);
  });

  it('fails loudly when the registry plans nothing for one spec', async () => {
    const { useCase, resolver } = harness();
    resolver.planFor({
      resolutions: [],
      hitCount: 0,
      missCount: 0,
      totalEstimatedNanoUsd: 0,
      requiresConfirmation: false,
    });

    const failed = await useCase.execute({
      spec: threeBlobSpec(),
      style: styleBible(),
      runId: RUN_ID,
    });
    expect(isErr(failed)).toBe(true);
  });

  it('refuses before the provider when the style is not locked', async () => {
    const { useCase, images, budget } = harness();
    const failed = await useCase.execute({
      spec: threeBlobSpec(),
      style: styleBible({ lockedAt: null }),
      runId: RUN_ID,
    });

    expect(isErr(failed)).toBe(true);
    expect(images.callCount).toBe(0);
    // Composition happens before the budget check, so a bad style costs no ledger row.
    expect(budget.checks).toHaveLength(0);
  });

  it('records a failure row and returns the provider error', async () => {
    const images = new FakeImagePort();
    const rows: string[] = [];
    images.failWith(new ProviderError({ message: 'upstream 500', provider: 'fake' }));

    const failed = await new GenerateAssetVersionUseCase({
      resolver: new FakeResolver(),
      budget: new FakeBudget(),
      images,
      blobs: new InMemoryBlobStore(),
      ledger: { record: (input) => rows.push(input.outcome) },
    }).execute({
      spec: threeBlobSpec(),
      style: styleBible(),
      runId: RUN_ID,
      binding: { provider: 'comfyui', model: 'dreamshaper_8' },
    });

    expect(isErr(failed)).toBe(true);
    expect(rows).toEqual(['failure']);
  });

  it('records a success row with the tier the spec asked for', async () => {
    const rows: { tier: string; task: string; outcome: string }[] = [];
    const result = await new GenerateAssetVersionUseCase({
      resolver: new FakeResolver(),
      budget: new FakeBudget(),
      images: new FakeImagePort(),
      blobs: new InMemoryBlobStore(),
      ledger: {
        record: (input) =>
          rows.push({ tier: input.tier, task: input.task, outcome: input.outcome }),
      },
    }).execute({
      spec: threeBlobSpec({ quality: 'final' }),
      style: styleBible(),
      runId: RUN_ID,
      binding: { provider: 'gemini', model: 'gemini-3.1-flash-lite-image' },
    });

    expect(isOk(result)).toBe(true);
    expect(rows).toEqual([{ tier: 'final', task: 'image-final', outcome: 'success' }]);
  });

  it('treats an empty image list as a provider failure', async () => {
    const { useCase, images } = harness();
    images.returnNoImages();
    expect(
      isErr(await useCase.execute({ spec: threeBlobSpec(), style: styleBible(), runId: RUN_ID })),
    ).toBe(true);
  });

  it('passes the variant key through to the registry', async () => {
    const { useCase, resolver } = harness();
    await useCase.execute({
      spec: threeBlobSpec(),
      style: styleBible(),
      runId: RUN_ID,
      variantKey: 'winter',
    });
    expect(resolver.calls[0]?.styleChecksum).toBe(styleBible().checksum);
  });
});

describe('GenerateAssetVersionUseCase, parts-sheet routing', () => {
  function sheetHarness(port: FakeImagePort): GenerateAssetVersionUseCase {
    return new GenerateAssetVersionUseCase({
      resolver: new FakeResolver(),
      budget: new FakeBudget(),
      images: port,
      blobs: new InMemoryBlobStore(),
    });
  }

  it('sends the slots to a port that serves parts sheets, and never the prose prompt', async () => {
    const port = new FakePartsSheetPort();
    const result = unwrap(
      await sheetHarness(port).execute({
        spec: threeBlobSpec(),
        style: styleBible(),
        runId: RUN_ID,
        background: 'flat solid cream',
      }),
    );

    expect(port.sheetRequests).toHaveLength(1);
    const sheet = port.sheetRequests[0];
    expect(sheet?.parts).toEqual(['base', 'segment-1', 'segment-2']);
    expect(sheet?.background).toBe('flat solid cream');
    // Three parts: two columns, two rows. Advisory, and still the number the graph gets.
    expect(sheet?.grid).toEqual({ cols: 2, rows: 2 });
    expect(sheet?.subject).toBe('A dented brass lantern in three pieces.');
    // The prose layout clause exists for the fallback path and must not be duplicated
    // into the slot request, where the workflow already owns it.
    expect(sheet?.subject).not.toContain('parts sheet');
    expect(result.outcome).toBe('generated');
    if (result.outcome === 'generated') expect(result.degraded).toEqual([]);
  });

  it('falls back to generateImage and says so when the port cannot serve a sheet', async () => {
    const port = new FakeImagePort();
    const result = unwrap(
      await sheetHarness(port).execute({
        spec: threeBlobSpec(),
        style: styleBible(),
        runId: RUN_ID,
      }),
    );

    expect(port.requests[0]?.prompt).toContain('parts sheet');
    expect(result.outcome).toBe('generated');
    if (result.outcome !== 'generated') return;
    expect(result.degraded.filter((entry) => entry.includes('parts-sheet graph'))).toHaveLength(1);
  });

  it('treats a declared-but-unavailable graph as no graph at all', async () => {
    const port = new FakePartsSheetPort();
    port.servesPartsSheet = false;

    const result = unwrap(
      await sheetHarness(port).execute({
        spec: threeBlobSpec(),
        style: styleBible(),
        runId: RUN_ID,
      }),
    );

    expect(port.sheetRequests).toHaveLength(0);
    expect(port.requests).toHaveLength(1);
    if (result.outcome === 'generated') {
      expect(result.degraded.filter((entry) => entry.includes('parts-sheet graph'))).toHaveLength(
        1,
      );
    }
  });

  it('leaves a single-part spec on the ordinary image path', async () => {
    const port = new FakePartsSheetPort();
    const spec = threeBlobSpec({
      parts: [
        {
          name: 'body',
          role: 'body',
          description: 'the whole thing',
          zOrder: 0,
          attachHint: { x: 0.5, y: 0.5 },
          deformable: false,
          optional: false,
        },
      ],
    });

    const result = unwrap(
      await sheetHarness(port).execute({ spec, style: styleBible(), runId: RUN_ID }),
    );

    expect(port.sheetRequests).toHaveLength(0);
    expect(port.requests).toHaveLength(1);
    // Routing around the sheet was the policy's decision, not a missing capability, so
    // nothing is degraded.
    if (result.outcome === 'generated') expect(result.degraded).toEqual([]);
  });
});

describe('GenerateAssetVersionUseCase, pricing before spending', () => {
  it('guards against the port quote rather than the plan flat rate', async () => {
    const { useCase, images, budget } = harness();
    images.quote = {
      kind: 'estimated',
      modelRef: 'openrouter:google/gemini-3.1-flash-lite-image',
      nanoUsd: nanoUsd(33_600_000),
      basis: 'test',
    };

    await useCase.execute({ spec: threeBlobSpec(), style: styleBible(), runId: RUN_ID });

    expect(images.quotes).toHaveLength(1);
    // The canvas the composer chose, so the quote is for the picture actually ordered.
    expect(images.quotes[0]?.size).toEqual(threeBlobSpec().canvas);
    expect(budget.checks).toEqual([33_600_000]);
  });

  it('asks for the price before it makes the call, not after', async () => {
    const { useCase, images } = harness();
    const order: string[] = [];
    const realQuote = images.quoteImage.bind(images);
    images.quoteImage = (request) => {
      order.push('quote');
      return realQuote(request);
    };
    const realGenerate = images.generateImage.bind(images);
    images.generateImage = async (request) => {
      order.push('generate');
      return realGenerate(request);
    };

    await useCase.execute({ spec: threeBlobSpec(), style: styleBible(), runId: RUN_ID });

    expect(order).toEqual(['quote', 'generate']);
  });

  it('refuses an unpriceable model rather than guessing, and spends nothing', async () => {
    const { useCase, images, budget } = harness();
    images.quote = {
      kind: 'unpriced',
      modelRef: 'openrouter:brand-new/model',
      reason: 'the catalogue has no image rate for this model',
    };

    const outcome = await useCase.execute({
      spec: threeBlobSpec(),
      style: styleBible(),
      runId: RUN_ID,
    });

    expect(isErr(outcome)).toBe(true);
    if (isErr(outcome)) expect(outcome.error.kind).toBe('validation');
    // The guard cannot run, so the call must not happen - and the guard is not asked
    // to rule on a number nobody has.
    expect(images.callCount).toBe(0);
    expect(budget.checks).toHaveLength(0);
  });

  it('records the quote beside the usage so projection and invoice can be compared', async () => {
    const { useCase } = harness();
    const result = unwrap(
      await useCase.execute({ spec: threeBlobSpec(), style: styleBible(), runId: RUN_ID }),
    );

    expect(result.outcome).toBe('generated');
    if (result.outcome !== 'generated') return;
    expect(result.quote.kind).toBe('free');
    expect(result.quote.modelRef).toBe('fake:image');
  });
});
