import { describe, expect, it } from 'vitest';
import {
  BudgetExceededError,
  InternalError,
  ProviderError,
  isErr,
  isOk,
  unwrap,
} from '@rv/shared-kernel';
import type { AssetDemandPlan, AssetId, AssetKey, AssetVersionId, RunId } from '@rv/contracts';

import {
  FakeBudget,
  FakeImagePort,
  FakeResolver,
  InMemoryBlobStore,
} from '../__fixtures__/doubles';
import { HASH_A, styleBible, threeBlobSpec } from '../__fixtures__/builders';
import { GenerateAssetVersionUseCase } from './generate-asset-version';

const RUN_ID = 'run_01J8ZQ4E7K9M2N4P6R8T0V2W4X' as RunId;
const KEY = 'c'.repeat(64) as AssetKey;
const ASSET_ID = 'ast_01J8ZQ4E7K9M2N4P6R8T0V2W4X' as AssetId;
const VERSION_ID = 'asv_01J8ZQ4E7K9M2N4P6R8T0V2W4X' as AssetVersionId;

function harness(): {
  useCase: GenerateAssetVersionUseCase;
  images: FakeImagePort;
  budget: FakeBudget;
  resolver: FakeResolver;
  blobs: InMemoryBlobStore;
} {
  const images = new FakeImagePort();
  const budget = new FakeBudget();
  const resolver = new FakeResolver();
  const blobs = new InMemoryBlobStore();
  return {
    useCase: new GenerateAssetVersionUseCase({ resolver, budget, images, blobs }),
    images,
    budget,
    resolver,
    blobs,
  };
}

function hitPlan(): AssetDemandPlan {
  return {
    resolutions: [
      {
        key: KEY,
        spec: threeBlobSpec(),
        outcome: 'cache-hit',
        existingAssetId: ASSET_ID,
        existingVersionId: VERSION_ID,
        styleBibleId: styleBible().id,
        estimatedCostNanoUsd: 0,
      },
    ],
    hitCount: 1,
    missCount: 0,
    totalEstimatedNanoUsd: 0,
    requiresConfirmation: false,
  };
}

describe('GenerateAssetVersionUseCase', () => {
  it('spends nothing on a cache hit: the image port receives zero calls', async () => {
    const { useCase, images, resolver, blobs } = harness();
    resolver.planFor(hitPlan());

    const result = unwrap(
      await useCase.execute({ spec: threeBlobSpec(), style: styleBible(), runId: RUN_ID }),
    );

    expect(result.outcome).toBe('cache-hit');
    // The whole of non-negotiable #2, as an assertion: no call, no bytes, no cost.
    expect(images.callCount).toBe(0);
    expect(blobs.puts).toHaveLength(0);
    if (result.outcome === 'cache-hit') expect(result.costNanoUsd).toBe(0);
  });

  it('generates past a hit only when a regenerate intent is presented', async () => {
    const { useCase, images, resolver } = harness();
    resolver.planFor(hitPlan());

    const result = unwrap(
      await useCase.execute({
        spec: threeBlobSpec(),
        style: styleBible(),
        runId: RUN_ID,
        regenerate: { reason: 'new-take' },
      }),
    );

    expect(result.outcome).toBe('generated');
    expect(images.callCount).toBe(1);
  });

  it('checks the budget before the provider, and refuses without calling it', async () => {
    const { useCase, images, budget } = harness();
    budget.refuseWith(new BudgetExceededError('run', 1, 2));

    const failed = await useCase.execute({
      spec: threeBlobSpec(),
      style: styleBible(),
      runId: RUN_ID,
    });

    expect(isErr(failed)).toBe(true);
    expect(images.callCount).toBe(0);
    expect(budget.checks).toHaveLength(1);
  });

  it('stores the generated bytes and returns their content hash', async () => {
    const { useCase, blobs } = harness();
    const result = unwrap(
      await useCase.execute({ spec: threeBlobSpec(), style: styleBible(), runId: RUN_ID }),
    );

    expect(result.outcome).toBe('generated');
    if (result.outcome !== 'generated') return;
    expect(blobs.puts).toContain(result.imageHash);
    expect(result.request.prompt).toContain('parts sheet');
  });

  it('reports a missing reference as degraded rather than dropping it silently', async () => {
    const { useCase } = harness();
    const spec = threeBlobSpec();
    const result = unwrap(
      await useCase.execute({
        spec,
        style: styleBible(),
        runId: RUN_ID,
        extraReferences: [{ imageHash: HASH_A, role: 'identity-anchor', weight: 1 }],
      }),
    );

    expect(result.outcome).toBe('generated');
    if (result.outcome !== 'generated') return;
    expect(result.degraded).toHaveLength(1);
    expect(result.degraded[0]).toContain('identity-anchor');
  });

  it('passes references it can load through to the provider', async () => {
    const { useCase, images, blobs } = harness();
    const stored = unwrap(await blobs.put(Uint8Array.from([9, 9, 9])));

    await useCase.execute({
      spec: threeBlobSpec(),
      style: styleBible(),
      runId: RUN_ID,
      extraReferences: [{ imageHash: stored.hash, role: 'style-anchor', weight: 1 }],
    });

    expect(images.requests[0]?.references).toHaveLength(1);
  });

  it('propagates a registry failure', async () => {
    const { useCase, resolver, images } = harness();
    resolver.failWith(new InternalError({ message: 'index unavailable' }));

    expect(
      isErr(await useCase.execute({ spec: threeBlobSpec(), style: styleBible(), runId: RUN_ID })),
    ).toBe(true);
    expect(images.callCount).toBe(0);
  });

  it('fails loudly when the registry plans nothing for one spec', async () => {
    const { useCase, resolver } = harness();
    resolver.planFor({
      resolutions: [],
      hitCount: 0,
      missCount: 0,
      totalEstimatedNanoUsd: 0,
      requiresConfirmation: false,
    });

    const failed = await useCase.execute({
      spec: threeBlobSpec(),
      style: styleBible(),
      runId: RUN_ID,
    });
    expect(isErr(failed)).toBe(true);
  });

  it('refuses before the provider when the style is not locked', async () => {
    const { useCase, images, budget } = harness();
    const failed = await useCase.execute({
      spec: threeBlobSpec(),
      style: styleBible({ lockedAt: null }),
      runId: RUN_ID,
    });

    expect(isErr(failed)).toBe(true);
    expect(images.callCount).toBe(0);
    // Composition happens before the budget check, so a bad style costs no ledger row.
    expect(budget.checks).toHaveLength(0);
  });

  it('records a failure row and returns the provider error', async () => {
    const images = new FakeImagePort();
    const rows: string[] = [];
    images.failWith(new ProviderError({ message: 'upstream 500', provider: 'fake' }));

    const failed = await new GenerateAssetVersionUseCase({
      resolver: new FakeResolver(),
      budget: new FakeBudget(),
      images,
      blobs: new InMemoryBlobStore(),
      ledger: { record: (input) => rows.push(input.outcome) },
    }).execute({
      spec: threeBlobSpec(),
      style: styleBible(),
      runId: RUN_ID,
      binding: { provider: 'comfyui', model: 'dreamshaper_8' },
    });

    expect(isErr(failed)).toBe(true);
    expect(rows).toEqual(['failure']);
  });

  it('records a success row with the tier the spec asked for', async () => {
    const rows: { tier: string; task: string; outcome: string }[] = [];
    const result = await new GenerateAssetVersionUseCase({
      resolver: new FakeResolver(),
      budget: new FakeBudget(),
      images: new FakeImagePort(),
      blobs: new InMemoryBlobStore(),
      ledger: {
        record: (input) =>
          rows.push({ tier: input.tier, task: input.task, outcome: input.outcome }),
      },
    }).execute({
      spec: threeBlobSpec({ quality: 'final' }),
      style: styleBible(),
      runId: RUN_ID,
      binding: { provider: 'gemini', model: 'gemini-3.1-flash-lite-image' },
    });

    expect(isOk(result)).toBe(true);
    expect(rows).toEqual([{ tier: 'final', task: 'image-final', outcome: 'success' }]);
  });

  it('treats an empty image list as a provider failure', async () => {
    const { useCase, images } = harness();
    images.returnNoImages();
    expect(
      isErr(await useCase.execute({ spec: threeBlobSpec(), style: styleBible(), runId: RUN_ID })),
    ).toBe(true);
  });

  it('passes the variant key through to the registry', async () => {
    const { useCase, resolver } = harness();
    await useCase.execute({
      spec: threeBlobSpec(),
      style: styleBible(),
      runId: RUN_ID,
      variantKey: 'winter',
    });
    expect(resolver.calls[0]?.styleChecksum).toBe(styleBible().checksum);
  });
});
