/**
 * The curated shelf.
 *
 * Eleven complete styles, one per non-`custom` medium the pipeline has real phrasing
 * for. They are written as one file rather than eleven so that the thing that matters
 * most about them is reviewable: **every motion block is different, and different in a
 * way that follows from the medium.** Cut paper hinges and holds; watercolour drifts
 * and boils; a woodblock print holds for four frames and then changes all at once,
 * because that is what a stack of carved plates can physically do.
 *
 * Read the `motion` blocks down the file rather than across one preset. If two of them
 * ever start to look alike, `presets.spec.ts` will say so before a reviewer does.
 *
 * No preset carries prompt text. `toStylePreset` compiles it from `visual`.
 */

import type { StylePresetDefinition } from './preset';

export const PRESET_DEFINITIONS: readonly StylePresetDefinition[] = [
  // ── 1. flat vector ────────────────────────────────────────────────────────
  {
    id: 'flat-vector',
    name: { fa: 'برداری تخت', en: 'Flat Vector' },
    description: {
      fa: 'شکل‌های تخت و تمیز با لبه‌های برشی و رنگ‌های صاف؛ حرکت سریع، دقیق و بدون لرزش.',
      en: 'Clean flat shapes with knife-cut edges and solid colour. Motion is quick, precise and never wobbles.',
    },
    seed: 101_101,
    notes:
      'The cheapest style to generate and the most forgiving to rig: hard edges matte perfectly and flat fills survive part-splitting without seams.',
    visual: {
      medium: 'flat-vector',
      palette: {
        colors: [
          { name: 'signal', hex: '#f2542d', role: 'primary' },
          { name: 'deep-teal', hex: '#0e7c7b', role: 'secondary' },
          { name: 'sunbeam', hex: '#f5c04a', role: 'accent' },
          { name: 'slate', hex: '#2b2d42', role: 'shadow' },
          { name: 'bone', hex: '#f6f4ef', role: 'background' },
        ],
        harmony: 'complementary',
        contrastFloor: 0.55,
        organicRamp: ['#f0c8a0', '#c98a63', '#8a5a3c'],
      },
      line: {
        present: false,
        weight: 0,
        variability: 0,
        colorMode: 'none',
        taper: 0,
        roughness: 0,
      },
      shading: {
        model: 'flat',
        // One tone, because `flat` means no shading at all. A flat model with two bands
        // is two decisions that were never reconciled, and `checkStyleCoherence` says so.
        steps: 1,
        lightDirection: 45,
        rimLight: 0,
        occlusionStrength: 0.15,
      },
      texture: { grain: 0, paperFiber: 0, halftone: 0, edgeRoughness: 0, brushVisibility: 0 },
      shape: {
        roundness: 0.55,
        exaggeration: 0.45,
        headToBodyRatio: 5.5,
        silhouetteRule: 'Every character reads as a distinct solid black shape at 48px.',
        detailDensity: 0.2,
      },
      backgroundTreatment: 'flat-color',
      negative: ['photorealism', 'texture noise', 'soft shadows'],
    },
    motion: {
      fps: 24,
      stepMode: 'smooth',
      easings: [
        { name: 'snap', p1: { x: 0.2, y: 0 }, p2: { x: 0, y: 1 } },
        { name: 'glide', p1: { x: 0.4, y: 0 }, p2: { x: 0.2, y: 1 } },
      ],
      defaultEasing: 'snap',
      principles: {
        squashStretch: 0.15,
        anticipation: 0.3,
        followThrough: 0.25,
        overshoot: 0.35,
        secondaryMotion: 0.3,
        arcBias: 0.45,
        holdBias: 0.2,
        weight: 0.35,
      },
      boil: { enabled: false, amplitude: 0, hz: 8, affectsFills: false },
      ambient: {
        windHz: 0.5,
        windAmplitude: 0.15,
        windGustiness: 0.2,
        breathHz: 0.3,
        blinkIntervalMs: 3600,
        blinkVarianceMs: 1200,
        idleAmplitude: 0.1,
        phaseByDepth: 0.3,
      },
      camera: {
        panEase: 'glide',
        parallaxStrength: 0.35,
        parallaxCurve: 'linear',
        shakeAmplitude: 0.02,
        defaultShotMs: 2200,
        cutRhythm: 'brisk',
        allowZoom: true,
        allowRoll: false,
      },
      tempo: 1.15,
    },
    render: { filmGrain: 0, vignette: 0, bloom: 0, colorGrade: { saturation: 1.05 } },
  },

  // ── 2. paper cutout ───────────────────────────────────────────────────────
  {
    id: 'paper-cutout',
    name: { fa: 'کاغذ بریده', en: 'Paper Cutout' },
    description: {
      fa: 'لایه‌های کاغذ پاره‌شده با سایهٔ کوتاه؛ حرکت لولایی و پله‌ای، با مکث‌های طولانی مثل تئاتر سایه.',
      en: 'Torn paper layers with a short hard shadow. Movement hinges and steps, holding between beats like a shadow-theatre puppet.',
    },
    seed: 202_202,
    notes:
      'Hinged joints only - this style has no squash, because paper does not squash. The long holds are the medium, not a budget saving.',
    visual: {
      medium: 'paper-cutout',
      palette: {
        colors: [
          { name: 'moss', hex: '#4a6b3f', role: 'primary' },
          { name: 'bark', hex: '#5a4632', role: 'secondary' },
          { name: 'clay', hex: '#c1694f', role: 'accent' },
          { name: 'oat', hex: '#e8ddc8', role: 'background' },
          { name: 'ash', hex: '#3a3a35', role: 'shadow' },
        ],
        harmony: 'earthy',
        contrastFloor: 0.45,
        organicRamp: ['#e2b48c', '#b9825c', '#7a5239'],
      },
      line: {
        present: false,
        weight: 0,
        variability: 0,
        colorMode: 'none',
        taper: 0,
        roughness: 0,
      },
      shading: {
        model: 'flat',
        steps: 1,
        lightDirection: 100,
        ambientTint: '#5a4632',
        rimLight: 0,
        occlusionStrength: 0.6,
      },
      texture: {
        grain: 0.15,
        paperFiber: 0.75,
        halftone: 0,
        edgeRoughness: 0.8,
        brushVisibility: 0,
      },
      shape: {
        roundness: 0.4,
        exaggeration: 0.5,
        headToBodyRatio: 4.5,
        silhouetteRule:
          'Every part must survive being cut out with scissors: no shape narrower than a finger.',
        detailDensity: 0.25,
      },
      backgroundTreatment: 'layered-parallax',
      negative: ['photorealism', 'smooth gradient', 'anti-aliased edge'],
    },
    motion: {
      fps: 24,
      stepMode: 'on-2s',
      easings: [
        { name: 'hinge', p1: { x: 0.9, y: 0 }, p2: { x: 0.1, y: 1 } },
        { name: 'card-slide', p1: { x: 0.85, y: 0 }, p2: { x: 0.15, y: 1 } },
      ],
      defaultEasing: 'hinge',
      principles: {
        squashStretch: 0.05,
        anticipation: 0.55,
        followThrough: 0.2,
        overshoot: 0.3,
        secondaryMotion: 0.25,
        arcBias: 0.15,
        holdBias: 0.7,
        weight: 0.55,
      },
      boil: { enabled: false, amplitude: 0, hz: 8, affectsFills: false },
      ambient: {
        windHz: 0.8,
        windAmplitude: 0.45,
        windGustiness: 0.85,
        breathHz: 0.2,
        blinkIntervalMs: 5200,
        blinkVarianceMs: 2400,
        idleAmplitude: 0.15,
        phaseByDepth: 0.75,
      },
      camera: {
        panEase: 'card-slide',
        parallaxStrength: 0.65,
        parallaxCurve: 'linear',
        shakeAmplitude: 0.04,
        defaultShotMs: 3000,
        cutRhythm: 'measured',
        allowZoom: false,
        allowRoll: false,
      },
      tempo: 1,
    },
    render: { filmGrain: 0.12, vignette: 0.15, bloom: 0, colorGrade: { temperature: 0.1 } },
  },

  // ── 3. ink comic ──────────────────────────────────────────────────────────
  {
    id: 'ink-comic',
    name: { fa: 'مرکب و قلم‌مو', en: 'Ink Comic' },
    description: {
      fa: 'خط مرکبی قاطع با سیاهی‌های تخت؛ حرکت ضربه‌ای با شتاب ناگهانی، مکث‌های نمایشی و لرزش خط.',
      en: 'Confident brush-ink line with solid blacks. Movement snaps, overshoots and holds dramatically, and the line boils as it would if it were redrawn.',
    },
    seed: 303_303,
    notes:
      'The only preset with camera roll enabled: a dutch tilt is comic-book grammar, and forbidding it here would flatten the one thing the medium does best.',
    visual: {
      medium: 'ink-comic',
      palette: {
        colors: [
          { name: 'ink', hex: '#14110f', role: 'shadow' },
          { name: 'paper', hex: '#f0e9dc', role: 'background' },
          { name: 'blood', hex: '#a41623', role: 'accent' },
          { name: 'dusk-blue', hex: '#3d5a80', role: 'primary' },
          { name: 'ochre', hex: '#c9873a', role: 'secondary' },
        ],
        harmony: 'high-contrast',
        contrastFloor: 0.7,
        organicRamp: ['#e6c8a8', '#b98a63'],
      },
      line: {
        present: true,
        weight: 0.75,
        variability: 0.85,
        colorMode: 'black',
        taper: 0.8,
        roughness: 0.35,
      },
      shading: {
        model: 'crosshatch',
        steps: 3,
        lightDirection: 135,
        rimLight: 0.3,
        occlusionStrength: 0.75,
      },
      texture: {
        grain: 0.2,
        paperFiber: 0.35,
        halftone: 0.45,
        edgeRoughness: 0.3,
        brushVisibility: 0.5,
      },
      shape: {
        roundness: 0.3,
        exaggeration: 0.65,
        headToBodyRatio: 7,
        silhouetteRule: 'Poses read as a single dramatic gesture line from head to trailing foot.',
        detailDensity: 0.6,
      },
      backgroundTreatment: 'minimal',
      negative: ['soft airbrush', 'pastel colours', 'photographic lighting'],
    },
    motion: {
      fps: 24,
      stepMode: 'on-2s',
      easings: [
        { name: 'whip', p1: { x: 0.7, y: 0 }, p2: { x: 0.1, y: 1.35 } },
        { name: 'settle', p1: { x: 0.25, y: 1.4 }, p2: { x: 0.4, y: 1 } },
      ],
      defaultEasing: 'whip',
      principles: {
        squashStretch: 0.45,
        anticipation: 0.75,
        followThrough: 0.55,
        overshoot: 0.6,
        secondaryMotion: 0.45,
        arcBias: 0.7,
        holdBias: 0.65,
        weight: 0.6,
      },
      boil: { enabled: true, amplitude: 0.25, hz: 12, affectsFills: false },
      ambient: {
        windHz: 0.4,
        windAmplitude: 0.2,
        windGustiness: 0.6,
        breathHz: 0.35,
        blinkIntervalMs: 2800,
        blinkVarianceMs: 900,
        idleAmplitude: 0.08,
        phaseByDepth: 0.4,
      },
      camera: {
        panEase: 'settle',
        parallaxStrength: 0.55,
        parallaxCurve: 'exponential',
        shakeAmplitude: 0.18,
        defaultShotMs: 1800,
        cutRhythm: 'frenetic',
        allowZoom: true,
        allowRoll: true,
      },
      tempo: 1.25,
    },
    render: { filmGrain: 0.25, vignette: 0.3, bloom: 0, colorGrade: { saturation: 0.85 } },
  },

  // ── 4. watercolour ────────────────────────────────────────────────────────
  {
    id: 'watercolour',
    name: { fa: 'آبرنگ', en: 'Watercolour' },
    description: {
      fa: 'لکه‌های آبرنگ که در کاغذ می‌دوند و لبه‌هایشان می‌شکفد؛ حرکت نرم و شناور با جوش زیاد رنگ.',
      en: 'Washes that run into the paper and bloom at the edge. Movement is soft, floaty and arcs through everything, with a high slow boil.',
    },
    seed: 404_404,
    notes:
      'Highest boil amplitude in the library and the lowest weight: nothing here lands hard, because a wet edge cannot.',
    visual: {
      medium: 'watercolour',
      palette: {
        colors: [
          { name: 'wash-blue', hex: '#7fa6c9', role: 'primary' },
          { name: 'wash-rose', hex: '#d99a9a', role: 'secondary' },
          { name: 'leaf-wash', hex: '#9bb886', role: 'accent' },
          { name: 'sepia-pool', hex: '#8a7256', role: 'shadow' },
          { name: 'cold-press', hex: '#fbf8f1', role: 'background' },
        ],
        harmony: 'muted',
        contrastFloor: 0.3,
        organicRamp: ['#f2d6c2', '#dfae95', '#b9836a'],
      },
      line: {
        present: true,
        weight: 0.2,
        variability: 0.7,
        colorMode: 'darker-fill',
        taper: 0.6,
        roughness: 0.65,
      },
      shading: {
        model: 'soft',
        steps: 3,
        lightDirection: 60,
        ambientTint: '#8fa8c4',
        rimLight: 0.1,
        occlusionStrength: 0.25,
      },
      texture: {
        grain: 0.25,
        paperFiber: 0.85,
        halftone: 0,
        edgeRoughness: 0.55,
        brushVisibility: 0.45,
      },
      shape: {
        roundness: 0.8,
        exaggeration: 0.35,
        headToBodyRatio: 6,
        silhouetteRule:
          'Silhouettes stay readable even where the wash escapes the drawing - the shape is the wash, not the line.',
        detailDensity: 0.35,
      },
      backgroundTreatment: 'painted',
      negative: ['hard vector edge', 'digital glow', 'heavy black outline'],
    },
    motion: {
      fps: 24,
      stepMode: 'smooth',
      easings: [
        { name: 'bleed', p1: { x: 0.35, y: 0 }, p2: { x: 0.35, y: 1 } },
        { name: 'drift', p1: { x: 0.5, y: 0 }, p2: { x: 0.5, y: 1 } },
      ],
      defaultEasing: 'bleed',
      principles: {
        squashStretch: 0.2,
        anticipation: 0.2,
        followThrough: 0.7,
        overshoot: 0.1,
        secondaryMotion: 0.75,
        arcBias: 0.9,
        holdBias: 0.35,
        weight: 0.2,
      },
      boil: { enabled: true, amplitude: 0.55, hz: 3, affectsFills: true },
      ambient: {
        windHz: 0.2,
        windAmplitude: 0.55,
        windGustiness: 0.15,
        breathHz: 0.18,
        blinkIntervalMs: 6000,
        blinkVarianceMs: 2600,
        idleAmplitude: 0.35,
        phaseByDepth: 0.85,
      },
      camera: {
        panEase: 'drift',
        parallaxStrength: 0.75,
        parallaxCurve: 'logarithmic',
        shakeAmplitude: 0.01,
        defaultShotMs: 5200,
        cutRhythm: 'languid',
        allowZoom: true,
        allowRoll: false,
      },
      tempo: 0.8,
    },
    render: {
      filmGrain: 0.1,
      vignette: 0.1,
      bloom: 0.15,
      colorGrade: { saturation: 0.9, temperature: -0.1 },
    },
  },

  // ── 5. gouache storybook ──────────────────────────────────────────────────
  {
    id: 'gouache-storybook',
    name: { fa: 'گواش کتاب کودک', en: 'Gouache Storybook' },
    description: {
      fa: 'رنگ گواش مات روی کاغذ رنگی؛ حرکت آرام و سنجیده روی سه فریم، مثل ورق‌زدن یک کتاب مصور.',
      en: 'Matte opaque gouache on toned paper. Movement is unhurried and stepped on threes, paced like turning the page of a picture book.',
    },
    seed: 505_505,
    notes:
      'The only `on-3s` preset. Combined with the longest shots and no zoom, it produces the deliberate, illustrated-page pacing the medium implies.',
    visual: {
      medium: 'gouache',
      palette: {
        colors: [
          { name: 'cornflower', hex: '#6a8caf', role: 'primary' },
          { name: 'apricot', hex: '#e8a87c', role: 'secondary' },
          { name: 'sage', hex: '#8ba888', role: 'accent' },
          { name: 'plum-shadow', hex: '#584b5e', role: 'shadow' },
          { name: 'toned-card', hex: '#e6dcc6', role: 'background' },
          { name: 'chalk-white', hex: '#faf6ee', role: 'highlight' },
        ],
        harmony: 'analogous',
        contrastFloor: 0.4,
        organicRamp: ['#f0cfae', '#d3a480', '#a97a58'],
      },
      line: {
        present: true,
        weight: 0.35,
        variability: 0.45,
        colorMode: 'tinted',
        taper: 0.35,
        roughness: 0.4,
      },
      shading: {
        model: 'cel',
        steps: 3,
        lightDirection: 30,
        ambientTint: '#584b5e',
        rimLight: 0.2,
        occlusionStrength: 0.4,
      },
      texture: {
        grain: 0.3,
        paperFiber: 0.5,
        halftone: 0,
        edgeRoughness: 0.35,
        brushVisibility: 0.6,
      },
      shape: {
        roundness: 0.7,
        exaggeration: 0.4,
        headToBodyRatio: 4,
        silhouetteRule: 'Characters read as friendly rounded masses; no spike longer than a hand.',
        detailDensity: 0.45,
      },
      backgroundTreatment: 'painted',
      negative: ['glossy highlight', 'neon colour', 'photographic depth of field'],
    },
    motion: {
      fps: 24,
      stepMode: 'on-3s',
      easings: [
        { name: 'page-turn', p1: { x: 0.45, y: 0 }, p2: { x: 0.15, y: 1 } },
        { name: 'linger', p1: { x: 0.6, y: 0 }, p2: { x: 0.4, y: 1 } },
      ],
      defaultEasing: 'page-turn',
      principles: {
        squashStretch: 0.25,
        anticipation: 0.35,
        followThrough: 0.45,
        overshoot: 0.2,
        secondaryMotion: 0.55,
        arcBias: 0.75,
        holdBias: 0.8,
        weight: 0.5,
      },
      boil: { enabled: true, amplitude: 0.2, hz: 4, affectsFills: true },
      ambient: {
        windHz: 0.25,
        windAmplitude: 0.3,
        windGustiness: 0.3,
        breathHz: 0.22,
        blinkIntervalMs: 5000,
        blinkVarianceMs: 1800,
        idleAmplitude: 0.2,
        phaseByDepth: 0.6,
      },
      camera: {
        panEase: 'linger',
        parallaxStrength: 0.5,
        parallaxCurve: 'logarithmic',
        shakeAmplitude: 0,
        defaultShotMs: 4600,
        cutRhythm: 'languid',
        allowZoom: false,
        allowRoll: false,
      },
      tempo: 0.75,
    },
    render: { filmGrain: 0.15, vignette: 0.2, bloom: 0, colorGrade: { saturation: 0.95 } },
  },

  // ── 6. pixel art ──────────────────────────────────────────────────────────
  {
    id: 'pixel-art',
    name: { fa: 'پیکسل‌آرت', en: 'Pixel Art' },
    description: {
      fa: 'پیکسل‌های دستی روی شبکهٔ سخت؛ حرکت روی ۱۲ فریم با خط‌های صاف، فشردگی زیاد و ضربهٔ دوربین.',
      en: 'Hand-placed pixels on a strict lattice. Twelve frames a second, straight-line moves, heavy squash and a camera that punches.',
    },
    seed: 606_606,
    notes:
      'Lowest arc bias in the library: pixels travel on the lattice, and an arc through a pixel grid is just an aliasing artefact.',
    visual: {
      medium: 'pixel-art',
      palette: {
        colors: [
          { name: 'crt-green', hex: '#5ab552', role: 'primary' },
          { name: 'arcade-blue', hex: '#4a7bd4', role: 'secondary' },
          { name: 'hot-pink', hex: '#e05a8a', role: 'accent' },
          { name: 'void', hex: '#1a1c2c', role: 'shadow' },
          { name: 'bit-cream', hex: '#f4f4ed', role: 'highlight' },
          { name: 'dust-purple', hex: '#5d275d', role: 'background' },
        ],
        harmony: 'triadic',
        contrastFloor: 0.65,
        organicRamp: ['#ffcd75', '#ef7d57', '#b13e53'],
      },
      line: {
        present: true,
        weight: 0.15,
        variability: 0,
        colorMode: 'darker-fill',
        taper: 0,
        roughness: 0,
      },
      shading: {
        model: 'cel',
        steps: 4,
        lightDirection: 135,
        rimLight: 0.35,
        occlusionStrength: 0.5,
      },
      texture: { grain: 0, paperFiber: 0, halftone: 0.2, edgeRoughness: 0, brushVisibility: 0 },
      shape: {
        roundness: 0.25,
        exaggeration: 0.7,
        headToBodyRatio: 2.5,
        silhouetteRule: 'Readable at 32px tall with no shape thinner than one pixel.',
        detailDensity: 0.3,
      },
      backgroundTreatment: 'layered-parallax',
      negative: ['anti-aliasing', 'motion blur', 'soft shadow', 'photographic texture'],
    },
    motion: {
      fps: 12,
      stepMode: 'on-2s',
      easings: [
        { name: 'step-snap', p1: { x: 0.9, y: 0 }, p2: { x: 1, y: 1 } },
        { name: 'arcade-pop', p1: { x: 0.3, y: 0 }, p2: { x: 0.1, y: 1.6 } },
      ],
      defaultEasing: 'arcade-pop',
      principles: {
        squashStretch: 0.6,
        anticipation: 0.65,
        followThrough: 0.3,
        overshoot: 0.55,
        secondaryMotion: 0.15,
        arcBias: 0.1,
        holdBias: 0.45,
        weight: 0.7,
      },
      boil: { enabled: false, amplitude: 0, hz: 8, affectsFills: false },
      ambient: {
        windHz: 1.5,
        windAmplitude: 0.2,
        windGustiness: 0.1,
        breathHz: 0.5,
        blinkIntervalMs: 2000,
        blinkVarianceMs: 400,
        idleAmplitude: 0.05,
        phaseByDepth: 0.15,
      },
      camera: {
        panEase: 'step-snap',
        parallaxStrength: 0.25,
        parallaxCurve: 'linear',
        shakeAmplitude: 0.12,
        defaultShotMs: 1500,
        cutRhythm: 'brisk',
        allowZoom: false,
        allowRoll: false,
      },
      tempo: 1.2,
    },
    render: { filmGrain: 0, vignette: 0.1, bloom: 0.2, colorGrade: { saturation: 1.15 } },
  },

  // ── 7. felt craft ─────────────────────────────────────────────────────────
  {
    id: 'felt-craft',
    name: { fa: 'نمد و پارچه', en: 'Felt Craft' },
    description: {
      fa: 'دیورامای نمدی دوخته‌شده با لبه‌های پرزدار؛ حرکت سنگین و نرم روی ۱۸ فریم با دنبالهٔ کشدار.',
      en: 'A stitched felt diorama with fuzzy fibre edges. Movement is heavy and soft at eighteen frames, with everything trailing behind the main mass.',
    },
    seed: 707_707,
    notes:
      'Heaviest style in the library apart from clay, and the only one at 18 fps - a compromise cadence that reads as handled rather than animated.',
    visual: {
      medium: 'felt-craft',
      palette: {
        colors: [
          { name: 'mustard-wool', hex: '#d9a441', role: 'primary' },
          { name: 'teal-felt', hex: '#3f7d78', role: 'secondary' },
          { name: 'berry-thread', hex: '#a8425c', role: 'accent' },
          { name: 'charcoal-wool', hex: '#3c3a36', role: 'shadow' },
          { name: 'undyed', hex: '#efe6d5', role: 'background' },
        ],
        harmony: 'earthy',
        contrastFloor: 0.4,
        organicRamp: ['#f3d3b3', '#d6a480', '#a3765a'],
      },
      line: {
        present: true,
        weight: 0.3,
        variability: 0.55,
        colorMode: 'tinted',
        taper: 0.15,
        roughness: 0.7,
      },
      shading: {
        model: 'soft',
        steps: 2,
        lightDirection: 75,
        ambientTint: '#3c3a36',
        rimLight: 0.45,
        occlusionStrength: 0.55,
      },
      texture: {
        grain: 0.4,
        paperFiber: 0.2,
        halftone: 0,
        edgeRoughness: 0.65,
        brushVisibility: 0.15,
      },
      shape: {
        roundness: 0.9,
        exaggeration: 0.5,
        headToBodyRatio: 3,
        silhouetteRule: 'Everything reads as something that could be cut from a single felt sheet.',
        detailDensity: 0.4,
      },
      backgroundTreatment: 'detailed-scene',
      negative: ['hard vector edge', 'glossy plastic', 'digital gradient'],
    },
    motion: {
      fps: 18,
      stepMode: 'on-2s',
      easings: [
        { name: 'plush', p1: { x: 0.3, y: 0 }, p2: { x: 0.2, y: 1.1 } },
        { name: 'nudge', p1: { x: 0.5, y: 0 }, p2: { x: 0.4, y: 1 } },
      ],
      defaultEasing: 'plush',
      principles: {
        squashStretch: 0.4,
        anticipation: 0.45,
        followThrough: 0.75,
        overshoot: 0.4,
        secondaryMotion: 0.7,
        arcBias: 0.65,
        holdBias: 0.4,
        weight: 0.8,
      },
      boil: { enabled: true, amplitude: 0.15, hz: 2, affectsFills: false },
      ambient: {
        windHz: 0.35,
        windAmplitude: 0.25,
        windGustiness: 0.45,
        breathHz: 0.28,
        blinkIntervalMs: 4600,
        blinkVarianceMs: 2000,
        idleAmplitude: 0.3,
        phaseByDepth: 0.55,
      },
      camera: {
        panEase: 'nudge',
        parallaxStrength: 0.45,
        parallaxCurve: 'exponential',
        shakeAmplitude: 0.06,
        defaultShotMs: 3400,
        cutRhythm: 'measured',
        allowZoom: true,
        allowRoll: false,
      },
      tempo: 0.95,
    },
    render: { filmGrain: 0.18, vignette: 0.25, bloom: 0.05, colorGrade: { temperature: 0.15 } },
  },

  // ── 8. chalk pastel ───────────────────────────────────────────────────────
  {
    id: 'chalk-pastel',
    name: { fa: 'پاستل گچی', en: 'Chalk Pastel' },
    description: {
      fa: 'پاستل خشک روی کاغذ زبر با گرد رنگ در هوا؛ حرکت سبک و مه‌آلود با جوش زیاد و لبه‌های پودری.',
      en: 'Dry pastel dragged over toothy paper with pigment dust in the air. Light, hazy movement with a strong boil and powdery edges.',
    },
    seed: 808_808,
    notes:
      'Highest idle amplitude of the drawn styles: dust never settles, so nothing in frame is ever completely still.',
    visual: {
      medium: 'chalk-pastel',
      palette: {
        colors: [
          { name: 'dusk-violet', hex: '#8e7cc3', role: 'primary' },
          { name: 'chalk-coral', hex: '#e8927c', role: 'secondary' },
          { name: 'mint-dust', hex: '#a8d5ba', role: 'accent' },
          { name: 'soot', hex: '#4a4453', role: 'shadow' },
          { name: 'sugar-paper', hex: '#d9d2c5', role: 'background' },
        ],
        harmony: 'pastel',
        contrastFloor: 0.28,
        organicRamp: ['#f5d5c0', '#dda98f'],
      },
      line: {
        present: true,
        weight: 0.5,
        variability: 0.75,
        colorMode: 'tinted',
        taper: 0.25,
        roughness: 0.85,
      },
      shading: {
        model: 'stipple',
        steps: 4,
        lightDirection: 200,
        ambientTint: '#8e7cc3',
        rimLight: 0.15,
        occlusionStrength: 0.35,
      },
      texture: {
        grain: 0.7,
        paperFiber: 0.65,
        halftone: 0.1,
        edgeRoughness: 0.75,
        brushVisibility: 0.3,
      },
      shape: {
        roundness: 0.65,
        exaggeration: 0.3,
        headToBodyRatio: 6.5,
        silhouetteRule: 'Forms read from their mass, not their edge - the edge is always soft.',
        detailDensity: 0.35,
      },
      backgroundTreatment: 'gradient',
      negative: ['glossy surface', 'sharp vector edge', 'saturated neon'],
    },
    motion: {
      fps: 24,
      stepMode: 'on-2s',
      easings: [
        { name: 'smudge', p1: { x: 0.42, y: 0 }, p2: { x: 0.3, y: 1 } },
        { name: 'dust-drift', p1: { x: 0.55, y: 0 }, p2: { x: 0.45, y: 1 } },
      ],
      defaultEasing: 'smudge',
      principles: {
        squashStretch: 0.3,
        anticipation: 0.25,
        followThrough: 0.5,
        overshoot: 0.15,
        secondaryMotion: 0.6,
        arcBias: 0.55,
        holdBias: 0.3,
        weight: 0.3,
      },
      boil: { enabled: true, amplitude: 0.6, hz: 6, affectsFills: true },
      ambient: {
        windHz: 0.6,
        windAmplitude: 0.35,
        windGustiness: 0.55,
        breathHz: 0.24,
        blinkIntervalMs: 4200,
        blinkVarianceMs: 1600,
        idleAmplitude: 0.4,
        phaseByDepth: 0.65,
      },
      camera: {
        panEase: 'dust-drift',
        parallaxStrength: 0.6,
        parallaxCurve: 'exponential',
        shakeAmplitude: 0.05,
        defaultShotMs: 3800,
        cutRhythm: 'measured',
        allowZoom: true,
        allowRoll: true,
      },
      tempo: 0.9,
    },
    render: {
      filmGrain: 0.35,
      vignette: 0.22,
      bloom: 0.1,
      colorGrade: { saturation: 0.88, tint: 0.05 },
    },
  },

  // ── 9. painterly ──────────────────────────────────────────────────────────
  {
    id: 'painterly',
    name: { fa: 'نقاشی رنگ‌روغن', en: 'Painterly' },
    description: {
      fa: 'ضربه‌قلم‌های آشکار و نور غنی؛ حرکت پیوسته و کاملاً قوسی روی ۳۰ فریم با ثانویهٔ بسیار زیاد.',
      en: 'Visible directional brushwork and rich light. Continuous thirty-frame motion, everything travelling on an arc, with the strongest secondary motion in the library.',
    },
    seed: 909_909,
    notes:
      'The only 30 fps preset. Painted frames have no stepping to hide behind, so smoothness is doing the work the medium expects.',
    visual: {
      medium: 'painterly',
      palette: {
        colors: [
          { name: 'burnt-sienna', hex: '#9c4a2f', role: 'primary' },
          { name: 'prussian', hex: '#25415c', role: 'secondary' },
          { name: 'naples-yellow', hex: '#e6c47a', role: 'accent' },
          { name: 'umber', hex: '#3b2f26', role: 'shadow' },
          { name: 'linen-ground', hex: '#ddd2bd', role: 'background' },
          { name: 'lead-white', hex: '#f7f3e8', role: 'highlight' },
        ],
        harmony: 'split-complementary',
        contrastFloor: 0.5,
        organicRamp: ['#f0cdb0', '#cf9a78', '#9d6a4d', '#6b4632'],
      },
      line: {
        present: false,
        weight: 0,
        variability: 0,
        colorMode: 'none',
        taper: 0,
        roughness: 0,
      },
      shading: {
        model: 'painterly',
        steps: 5,
        lightDirection: 20,
        ambientTint: '#25415c',
        rimLight: 0.55,
        occlusionStrength: 0.65,
      },
      texture: {
        grain: 0.2,
        paperFiber: 0.15,
        halftone: 0,
        edgeRoughness: 0.45,
        brushVisibility: 0.9,
      },
      shape: {
        roundness: 0.6,
        exaggeration: 0.25,
        headToBodyRatio: 7.5,
        silhouetteRule: 'The value pattern carries the read; the silhouette alone need not.',
        detailDensity: 0.7,
      },
      backgroundTreatment: 'painted',
      negative: ['flat vector fill', 'hard cel shadow', 'pixel grid'],
    },
    motion: {
      fps: 30,
      stepMode: 'smooth',
      easings: [
        { name: 'oil-drift', p1: { x: 0.3, y: 0 }, p2: { x: 0.25, y: 1 } },
        { name: 'swell', p1: { x: 0.45, y: 0 }, p2: { x: 0.3, y: 1 } },
      ],
      defaultEasing: 'oil-drift',
      principles: {
        squashStretch: 0.25,
        anticipation: 0.4,
        followThrough: 0.65,
        overshoot: 0.25,
        secondaryMotion: 0.8,
        arcBias: 0.85,
        holdBias: 0.25,
        weight: 0.55,
      },
      boil: { enabled: false, amplitude: 0, hz: 8, affectsFills: false },
      ambient: {
        windHz: 0.3,
        windAmplitude: 0.4,
        windGustiness: 0.35,
        breathHz: 0.26,
        blinkIntervalMs: 4800,
        blinkVarianceMs: 2200,
        idleAmplitude: 0.25,
        phaseByDepth: 0.9,
      },
      camera: {
        panEase: 'swell',
        parallaxStrength: 0.85,
        parallaxCurve: 'exponential',
        shakeAmplitude: 0.03,
        defaultShotMs: 4200,
        cutRhythm: 'languid',
        allowZoom: true,
        allowRoll: true,
      },
      tempo: 0.9,
    },
    render: {
      filmGrain: 0.08,
      vignette: 0.35,
      bloom: 0.25,
      colorGrade: { saturation: 1.02, temperature: 0.08 },
    },
  },

  // ── 10. claymation ────────────────────────────────────────────────────────
  {
    id: 'claymation',
    name: { fa: 'خمیربازی', en: 'Claymation' },
    description: {
      fa: 'مدل‌های خمیری با اثر انگشت روی سطح؛ حرکت ۱۲ فریمی با فشردگی شدید، وزن زیاد و لرزش اسکلت.',
      en: 'Plasticine models with thumbprints in the surface. Twelve-frame movement with extreme squash, the heaviest weight in the library, and an armature that never quite holds still.',
    },
    seed: 111_011,
    notes:
      'Boil is enabled here even though clay has no line: it stands in for the frame-to-frame armature drift of real stop motion, which is the tell that separates it from CG.',
    visual: {
      medium: 'claymation',
      palette: {
        colors: [
          { name: 'putty-orange', hex: '#e07a3f', role: 'primary' },
          { name: 'clay-blue', hex: '#4c7a94', role: 'secondary' },
          { name: 'pea-green', hex: '#8fae54', role: 'accent' },
          { name: 'grey-clay', hex: '#575149', role: 'shadow' },
          { name: 'studio-cyc', hex: '#cfc7b8', role: 'background' },
        ],
        harmony: 'complementary',
        contrastFloor: 0.42,
        organicRamp: ['#f2c4a0', '#cf9370', '#96634a'],
      },
      line: {
        present: false,
        weight: 0,
        variability: 0,
        colorMode: 'none',
        taper: 0,
        roughness: 0,
      },
      shading: {
        model: 'soft',
        steps: 4,
        lightDirection: 300,
        ambientTint: '#4c7a94',
        rimLight: 0.6,
        occlusionStrength: 0.7,
      },
      texture: {
        grain: 0.12,
        paperFiber: 0,
        halftone: 0,
        edgeRoughness: 0.4,
        brushVisibility: 0.35,
      },
      shape: {
        roundness: 0.85,
        exaggeration: 0.6,
        headToBodyRatio: 3.5,
        silhouetteRule:
          'Every form must be something a thumb could actually make; no shape thinner than a pencil.',
        detailDensity: 0.5,
      },
      backgroundTreatment: 'detailed-scene',
      negative: ['flat vector fill', 'ink outline', 'pixel grid', 'perfectly smooth surface'],
    },
    motion: {
      fps: 12,
      stepMode: 'on-2s',
      easings: [
        { name: 'squish', p1: { x: 0.25, y: -0.3 }, p2: { x: 0.2, y: 1.25 } },
        { name: 'armature', p1: { x: 0.6, y: 0 }, p2: { x: 0.3, y: 1 } },
      ],
      defaultEasing: 'squish',
      principles: {
        squashStretch: 0.85,
        anticipation: 0.7,
        followThrough: 0.6,
        overshoot: 0.7,
        secondaryMotion: 0.35,
        arcBias: 0.6,
        holdBias: 0.55,
        weight: 0.9,
      },
      boil: { enabled: true, amplitude: 0.35, hz: 12, affectsFills: true },
      ambient: {
        windHz: 0.15,
        windAmplitude: 0.1,
        windGustiness: 0.25,
        breathHz: 0.4,
        blinkIntervalMs: 3000,
        blinkVarianceMs: 1400,
        idleAmplitude: 0.45,
        phaseByDepth: 0.35,
      },
      camera: {
        panEase: 'armature',
        parallaxStrength: 0.4,
        parallaxCurve: 'linear',
        shakeAmplitude: 0.09,
        defaultShotMs: 2800,
        cutRhythm: 'measured',
        allowZoom: true,
        allowRoll: false,
      },
      tempo: 0.85,
    },
    render: {
      filmGrain: 0.2,
      vignette: 0.28,
      bloom: 0.12,
      colorGrade: { saturation: 1.08, temperature: 0.12 },
    },
  },

  // ── 11. woodblock print ───────────────────────────────────────────────────
  {
    id: 'woodblock-print',
    name: { fa: 'چاپ چوبی', en: 'Woodblock Print' },
    description: {
      fa: 'چاپ بلوک چوبی با سطوح رنگ تخت و کمی جابه‌جایی صفحات؛ حرکت روی چهار فریم با مکث‌های بسیار طولانی.',
      en: 'Carved plates printed in flat colour with a slight registration shift. Movement steps on fours and holds longer than anything else in the library.',
    },
    seed: 121_012,
    notes:
      'Boil at 1.5 Hz with fills affected is not hand-drawn jitter - it is the plate registration shifting between impressions, which is the one thing a print does that a drawing cannot.',
    visual: {
      medium: 'woodblock',
      palette: {
        colors: [
          { name: 'indigo-plate', hex: '#2c3e5c', role: 'primary' },
          { name: 'vermilion-plate', hex: '#b53a2b', role: 'accent' },
          { name: 'tea-green', hex: '#7d8c5c', role: 'secondary' },
          { name: 'sumi', hex: '#221f1c', role: 'shadow' },
          { name: 'kozo-paper', hex: '#efe4cd', role: 'background' },
        ],
        harmony: 'muted',
        contrastFloor: 0.6,
        organicRamp: ['#e8c6a4', '#c1926c'],
      },
      line: {
        present: true,
        weight: 0.55,
        variability: 0.4,
        colorMode: 'black',
        taper: 0.5,
        roughness: 0.3,
      },
      shading: {
        model: 'flat',
        steps: 1,
        lightDirection: 90,
        rimLight: 0,
        occlusionStrength: 0.2,
      },
      texture: {
        grain: 0.35,
        paperFiber: 0.7,
        halftone: 0,
        edgeRoughness: 0.25,
        brushVisibility: 0.2,
      },
      shape: {
        roundness: 0.45,
        exaggeration: 0.2,
        headToBodyRatio: 8,
        silhouetteRule:
          'Every figure reads as a flat decorative shape first and a body second; no foreshortening.',
        detailDensity: 0.55,
      },
      backgroundTreatment: 'flat-color',
      negative: ['soft gradient', 'photographic lighting', 'volumetric shadow', 'perspective grid'],
    },
    motion: {
      fps: 24,
      stepMode: 'on-4s',
      easings: [
        { name: 'press', p1: { x: 0.95, y: 0 }, p2: { x: 0.05, y: 1 } },
        { name: 'slide-plate', p1: { x: 0.7, y: 0 }, p2: { x: 0.3, y: 1 } },
      ],
      defaultEasing: 'press',
      principles: {
        squashStretch: 0.05,
        anticipation: 0.15,
        followThrough: 0.1,
        overshoot: 0.05,
        secondaryMotion: 0.1,
        arcBias: 0.2,
        holdBias: 0.95,
        weight: 0.45,
      },
      boil: { enabled: true, amplitude: 0.1, hz: 1.5, affectsFills: true },
      ambient: {
        windHz: 0.1,
        windAmplitude: 0.08,
        windGustiness: 0.05,
        breathHz: 0.1,
        blinkIntervalMs: 8000,
        blinkVarianceMs: 3000,
        idleAmplitude: 0.03,
        phaseByDepth: 0.2,
      },
      camera: {
        panEase: 'slide-plate',
        parallaxStrength: 0.3,
        parallaxCurve: 'logarithmic',
        shakeAmplitude: 0,
        defaultShotMs: 6000,
        cutRhythm: 'languid',
        allowZoom: false,
        allowRoll: false,
      },
      tempo: 0.7,
    },
    render: { filmGrain: 0.22, vignette: 0.12, bloom: 0, colorGrade: { saturation: 0.92 } },
  },
];
